### ISSUE TITLE
Roadmap V1.0

### ISSUE THREAD

**Issue by 7leodev** [7leodev/UniversalSky#1]
## Lang:

- [x] GDScript Full Source Code.
- [x] Godot Shader Lang Full Source Code.
---------------------------------------------------------------------

## Rendering:

- [x] GLES3 Support.

## Sky
**DeepSpace:**

- [x] Background Panorama.
- [x] Stars Field Panorama.

**NearSpace:**

- [x] SunDisk.
- [x] Realistic Moon and Moon Phases.
- [x] Solar Eclipses.

**Atmosphere:**

- [x] ATI Paper Based Atmospheric Scattering.
- [x] NIght Scattering.
- [x] Semi Artistic Control.

**Clouds:**

- [x] Dynamic Clouds.
---------------------------------------------------------------------
## Lighting:
- [x] Sun and Moon Light Control.
- [ ] Post Processing Fog.
---------------------------------------------------------------------

## Time Of Day

**DateTime:**

- [x] Gregorian Calendar Support.
- [x] System Synchronization.
- [x] Speed Control.

**Celestial Positions:**

- [x] Coordinates Based on DateTime.
- [x] Sun And Moon Position Calculations.

---------------------------------------------------------------------
